// ============================================================
// Configuración central — datos fallback si Sanity no responde
// ============================================================

// ── Fotos reales de la web actual (WordPress) ──
const WP = 'https://reformat-venezuela.online/wp-content/uploads';

// ── WhatsApp actual ──
export const waPhone = '+584227997043';

export const waLink = (premsg = 'Hola, quiero información sobre sus servicios de remodelación') =>
  `https://wa.me/${waPhone.replace(/[^\d]/g, '')}?text=${encodeURIComponent(premsg)}`;

export const siteConfig = {
  name: 'ReformaT Venezuela',
  tagline: 'Remodelaciones Premium en Carabobo',
  address: 'San Diego & Valencia, Carabobo',
  phone: '+58 422 799 7043',
  phoneRaw: '+584227997043',
  phoneWa: '+584227997043',
  email: 'info@reformat-venezuela.online',
  whatsapp: waPhone,
  schedule: 'Lun - Vie: 8am - 5pm | Sáb: 8am - 12pm',
  url: 'https://reformat-venezuela.online',
  years: '20',
  projects: '150',
}

export const services = [
  {
    id: 'cocinas',
    slug: 'cocinas',
    path: '/servicios/cocinas',
    title: 'Remodelación de Cocina',
    name: 'Cocina',
    shortDescription: 'Renovamos tu cocina con funcionalidad y diseño moderno adaptado a tus gustos. Gabinetes, encimeras, iluminación y acabados premium en San Diego y Valencia, Carabobo.',
    shortDesc: 'Diseño y remodelación de cocinas modernas y funcionales.',
    fullDescription: 'Transformamos tu cocina en el corazón de tu hogar. Nuestro equipo de diseñadores y constructores trabaja contigo para crear espacios que combinan funcionalidad, estética y calidad premium.',
    longDescription: 'La cocina es donde la familia se reúne, se cocinan los mejores momentos y se crean recuerdos. Por eso, en **ReformaT Venezuela** nos especializamos en **remodelación de cocinas en San Diego y Valencia**, Carabobo. Nos encargamos de todo: desde el diseño inicial hasta los acabados finales. Trabajamos con gabinetes a medida, encimeras de granito o cuarzo, iluminación LED integrada y todo lo que necesitas para tener la cocina que siempre soñaste. Con más de 20 años de experiencia en reformas de cocinas, garantizamos un trabajo limpio, profesional y con resultados que superan tus expectativas.',
    summary: 'Reforma de cocinas con diseño moderno y acabados premium.',
    heroImage: `${WP}/2025/11/4f9e75a852947810e2fc262e92ceb26aaf4b9449.jpg`,
    timeline: '2–4 semanas',
    galleryImages: [
      `${WP}/2025/11/4f9e75a852947810e2fc262e92ceb26aaf4b9449.jpg`,
      `${WP}/2025/11/c11d4a42c2df886466dc228fe305556c5a1c7dce.jpg`,
      `${WP}/2025/11/a7074628ae5503c045cbce2a327c2ea08459cb11.jpg`,
    ],
    faqs: [
      { q: '¿Cuánto tiempo toma remodelar una cocina?', a: 'Depende del alcance. Una remodelación completa de cocina toma entre 2 y 4 semanas, incluyendo demolición, instalaciones y acabados.' },
      { q: '¿El diseño 3D tiene costo adicional?', a: 'No, el diseño 3D está incluido sin costo adicional en tu presupuesto.' },
      { q: '¿Trabajan con materiales que yo compre?', a: 'Sí, podemos trabajar con materiales propios o sugerirte los mejores proveedores en Carabobo.' },
    ],
    icon: 'UtensilsCrossed',
    iconName: 'UtensilsCrossed',
    features: [
      'Diseño 3D personalizado de tu cocina',
      'Gabinetes a medida con acabados premium',
      'Encimeras de granito, cuarzo o mármol',
      'Iluminación LED integrada',
      'Instalación de grifería y accesorios',
      'Plomería y electricidad incluidos',
      'Pintura y acabados finales',
    ],
    priceFrom: 'Consultar',
    order: 1,
  },
  {
    id: 'banos',
    slug: 'banos',
    path: '/servicios/banos',
    title: 'Remodelación de Baño',
    name: 'Baño',
    shortDescription: 'Creamos baños cómodos y elegantes, cuidando cada detalle para tu bienestar. Diseño moderno, azulejos premium y grifería de primera en Carabobo.',
    shortDesc: 'Remodelación de baños con acabados de primera.',
    fullDescription: 'Tu baño merece ser un santuario personal. Nos encargamos de todo: desde el diseño hasta los acabados finales.',
    longDescription: 'El baño es uno de los espacios más importantes de tu hogar. En **ReformaT Venezuela** nos especializamos en **remodelación de baños en San Diego, Valencia y toda el área de Carabobo**. Transformamos tu baño actual en un espacio moderno, funcional y confortable. Instalamos duchas a ras de suelo, vanities personalizados, porcelanatos de primera calidad, grifería moderna y todo lo necesario para que tu baño sea exactamente como lo imaginas. Nuestro equipo trabaja con orden y limpieza, respetando los plazos acordados y ofreciendo garantía en todos los trabajos.',
    summary: 'Diseño y remodelación de baños modernos y elegantes.',
    heroImage: `${WP}/2025/11/image-7.jpg`,
    timeline: '1–3 semanas',
    galleryImages: [
      `${WP}/2025/11/image-7.jpg`,
      `${WP}/2025/11/af78d08c764a5acd9a01ea460f3ceb209a99bdac.jpg`,
    ],
    faqs: [
      { q: '¿Cuánto tiempo toma remodelar un baño?', a: 'Una remodelación de baño puede tomar entre 1 y 3 semanas dependiendo de la complejidad del proyecto.' },
      { q: '¿Qué tipo de materiales utilizan?', a: 'Trabajamos con porcelanatos, cerámicas de primera calidad, grifería moderna y accesorios de los mejores proveedores.' },
      { q: '¿Puedo seguir usando el baño durante la obra?', a: 'Recomendamos tener un baño alternativo disponible durante la remodelación.' },
    ],
    icon: 'Bath',
    iconName: 'Bath',
    features: [
      'Diseño de baño moderno y funcional',
      'Duchas a ras de suelo con vidrio templado',
      'Vanities y gabinetes de baño a medida',
      'Instalación de porcelanatos y cerámicas',
      'Grifería y accesorios premium',
      'Impermeabilización y fontanería',
      'Iluminación y ventilación adecuada',
    ],
    priceFrom: 'Consultar',
    order: 2,
  },
  {
    id: 'electricos',
    slug: 'electricos',
    path: '/servicios/electricos',
    title: 'Servicios Eléctricos',
    name: 'Electricidad',
    shortDescription: 'Instalaciones eléctricas seguras y eficientes para tu hogar o negocio. Cuadro eléctrico, iluminación LED, tomas y domótica en Carabobo.',
    shortDesc: 'Instalaciones eléctricas seguras y modernas.',
    fullDescription: 'La electricidad es la columna vertebral de cualquier remodelación.',
    longDescription: 'Una **instalación eléctrica segura y eficiente** es fundamental para cualquier hogar o negocio. En **ReformaT Venezuela** ofrecemos **servicios eléctricos profesionales en San Diego y Valencia**, Carabobo. Nos encargamos de la instalación completa del cuadro eléctrico, iluminación LED empotrada y decorativa, tomas adicionales, cableado estructurado y sistemas de domótica. Todo nuestro trabajo cumple con las normativas eléctricas vigentes y garantizamos instalaciones seguras que protegen a tu familia y tus equipos eléctricos.',
    summary: 'Instalaciones eléctricas seguras, modernas y eficientes.',
    heroImage: `${WP}/2025/11/image-6.jpg`,
    timeline: '3–7 días',
    galleryImages: [
      `${WP}/2025/11/image-6.jpg`,
    ],
    faqs: [
      { q: '¿Hacen reparaciones eléctricas urgentes?', a: 'Sí, atendemos urgencias eléctricas y problemas que requieren atención inmediata.' },
      { q: '¿Pueden modernizar mi instalación eléctrica antigua?', a: 'Por supuesto. Actualizamos instalaciones antiguas para que sean seguras y eficientes.' },
    ],
    icon: 'Zap',
    iconName: 'Zap',
    features: [
      'Instalación de cuadro eléctrico nuevo',
      'Iluminación LED empotrada y decorativa',
      'Tomas de corriente adicionales',
      'Cableado estructurado para internet',
      'Sistemas de domótica y automatización',
      'Reparaciones y mantenimiento eléctrico',
    ],
    priceFrom: 'Consultar',
    order: 3,
  },
  {
    id: 'fontaneria',
    slug: 'fontaneria',
    path: '/servicios/fontaneria',
    title: 'Fontanería',
    name: 'Fontanería',
    shortDescription: 'Soluciones completas de fontanería con materiales de primera. Reparación de fugas, instalación de sanitarios y sistemas de filtrado en Venezuela.',
    shortDesc: 'Fontanería profesional y soluciones completas.',
    fullDescription: 'Fontanería profesional para cualquier proyecto de remodelación.',
    longDescription: 'La **fontanería** es esencial en cualquier proyecto de remodelación. En **ReformaT Venezuela** ofrecemos **servicios de fontanería profesional en Carabobo**. Instalamos tuberías de cobre y PEX de alta calidad, realizamos instalación completa de sanitarios, lavabos, duchas y bañeras. Nos especializamos en la detección y reparación de fugas e impermeabilización de áreas húmedas. Nuestro equipo de fontaneros garantiza un trabajo limpio, eficiente y con materiales de primera calidad que asegura la durabilidad de tu instalación.',
    summary: 'Fontanería profesional con materiales de primera.',
    heroImage: `${WP}/2025/11/image-6.jpg`,
    timeline: '3–7 días',
    galleryImages: [
      `${WP}/2025/11/image-7.jpg`,
    ],
    faqs: [
      { q: '¿Reparan fugas de agua?', a: 'Sí, diagnosticamos y reparamos fugas de agua con garantía.' },
      { q: '¿Trabajan con tuberías de PEX y cobre?', a: 'Sí, trabajamos con ambos tipos según las necesidades de tu proyecto.' },
    ],
    icon: 'Wrench',
    iconName: 'Wrench',
    features: [
      'Instalación de tuberías de cobre y PEX',
      'Instalación de sanitarios, lavabos y duchas',
      'Sistemas de filtrado de agua',
      'Detección y reparación de fugas',
      'Impermeabilización de áreas húmedas',
      'Mantenimiento preventivo de fontanería',
    ],
    priceFrom: 'Consultar',
    order: 4,
  },
  {
    id: 'integral',
    slug: 'integral',
    path: '/servicios/integral',
    title: 'Reforma Integral',
    name: 'Integral',
    shortDescription: 'Transformación completa de tu vivienda o local de inicio a fin. Diseño, demolición, construcción, instalaciones y acabados llave en mano en Carabobo.',
    shortDesc: 'Reforma completa de inicio a fin.',
    fullDescription: '¿Necesitas renovar tu vivienda por completo? Nos encargamos de absolutamente todo.',
    longDescription: 'Si necesitas una **renovación completa de tu vivienda o local comercial**, en **ReformaT Venezuela** nos encargamos de absolutamente todo. Nuestro servicio de **reforma integral en San Diego y Valencia** incluye: diseño personalizado del espacio, demolición controlada, reconstrucción, todas las instalaciones (eléctricas, fontanería, climatización) y acabados de primera calidad. Coordinamos todos los oficios para que tú no tengas que preocuparte por nada. Te entregamos tu espacio completamente transformado y listo para disfrutar. Llave en mano.',
    summary: 'Transformación completa llave en mano.',
    heroImage: `${WP}/2025/11/a7074628ae5503c045cbce2a327c2ea08459cb11.jpg`,
    timeline: '2–3 meses',
    galleryImages: [
      `${WP}/2025/11/a7074628ae5503c045cbce2a327c2ea08459cb11.jpg`,
      `${WP}/2025/11/c11d4a42c2df886466dc228fe305556c5a1c7dce.jpg`,
    ],
    faqs: [
      { q: '¿Qué incluye una reforma integral?', a: 'Diseño, demolición, construcción, todas las instalaciones (eléctrica, fontanería), pintura, pisos y acabados finales.' },
      { q: '¿Puedo vivir en la casa durante la reforma?', a: 'Depende del alcance. En reformas parciales es posible, pero en integrales recomendamos alojamiento alternativo.' },
      { q: '¿Gestionan los permisos de construcción?', a: 'Sí, nos encargamos de toda la gestión de permisos necesarios.' },
    ],
    icon: 'Building2',
    iconName: 'Building2',
    features: [
      'Diseño integral personalizado',
      'Demolición controlada y segura',
      'Todos los oficios coordinados',
      'Instalaciones completas (eléctrica, fontanería)',
      'Pintura, pisos y acabados finales',
      'Gestión de permisos de construcción',
      'Entrega llave en mano',
    ],
    priceFrom: 'Consultar',
    order: 5,
  },
  {
    id: 'pisos',
    slug: 'pisos',
    path: '/servicios/pisos',
    title: 'Pisos y Revestimientos',
    name: 'Pisos',
    shortDescription: 'Instalación profesional de pisos, porcelanatos, cerámicas, vinilo click y microcemento en San Diego, Valencia y toda Venezuela.',
    shortDesc: 'Instalación profesional de pisos y revestimientos.',
    fullDescription: 'El piso define el carácter de cualquier espacio.',
    longDescription: 'El **piso o revestimiento** define completamente el carácter de cualquier espacio. En **ReformaT Venezuela** instalamos todo tipo de pisos con nivelación perfecta y acabados impecables. Trabajamos con porcelanatos de gran formato, cerámicas decorativas, vinilo click de alta resistencia y microcemento para un acabado moderno y minimalista. Nuestro equipo de instaladores profesionales garantiza una instalación precisa, sin juntas visibles innecesarias y con una nivelación perfecta que asegura durabilidad y estética por años.',
    summary: 'Instalación profesional de todo tipo de pisos.',
    heroImage: `${WP}/2025/11/af78d08c764a5acd9a01ea460f3ceb209a99bdac.jpg`,
    timeline: '3–7 días',
    galleryImages: [
      `${WP}/2025/11/c11d4a42c2df886466dc228fe305556c5a1c7dce.jpg`,
    ],
    faqs: [
      { q: 'Qué tipo de pisos instalan?', a: 'Porcelanatos de gran formato, cerámicas, vinilo click, microcemento y más.' },
      { q: '¿Pueden instalar sobre el piso existente?', a: 'En muchos casos sí, evaluamos las condiciones actuales para determinar la mejor solución.' },
    ],
    icon: 'Layers',
    iconName: 'Layers',
    features: [
      'Porcelanatos de gran formato premium',
      'Cerámicas decorativas de diseño',
      'Vinilo click de alta resistencia',
      'Microcemento para acabados modernos',
      'Nivelación perfecta garantizada',
      'Revestimientos de paredes incluidos',
    ],
    priceFrom: 'Consultar',
    order: 6,
  },
  {
    id: 'pintura',
    slug: 'pintura',
    path: '/servicios/pintura',
    title: 'Pintura',
    name: 'Pintura',
    shortDescription: 'Pintura interior y exterior con acabados profesionales, estuco, texturas y microcemento decorativo en Venezuela.',
    shortDesc: 'Pintura con acabados profesionales y limpios.',
    fullDescription: 'El cambio más visible y económico para transformar un espacio.',
    longDescription: 'La **pintura** es el cambio más visible y económico para transformar cualquier espacio. En **ReformaT Venezuela** ofrecemos servicios de **pintura profesional en San Diego, Valencia y alrededores**. Trabajamos con pinturas plásticas premium, estucos decorativos, texturas de pared y microcemento para acabados modernos. Nuestro equipo prepara las superficies adecuadamente antes de pintar, garantizando un acabado uniforme, limpio y duradero. Ya sea para renovar el color de tu hogar o darle un toque modernista, tenemos la solución perfecta.',
    summary: 'Pintura profesional interior y exterior.',
    heroImage: `${WP}/2025/11/a7074628ae5503c045cbce2a327c2ea08459cb11.jpg`,
    timeline: '2–5 días',
    galleryImages: [
      `${WP}/2025/11/a7074628ae5503c045cbce2a327c2ea08459cb11.jpg`,
    ],
    faqs: [
      { q: '¿Usan pinturas ecológicas?', a: 'Sí, trabajamos con pinturas de bajo VOC respetuosas con el medio ambiente.' },
      { q: '¿Cuánto dura una buena pintura?', a: 'Con preparación adecuada y pintura premium, el acabado dura entre 5 y 10 años.' },
    ],
    icon: 'Paintbrush',
    iconName: 'Paintbrush',
    features: [
      'Pintura plástica premium interior y exterior',
      'Estuco y texturas decorativas',
      'Microcemento para pared',
      'Lacado de puertas y ventanas',
      'Preparación de superficies incluida',
      'Protección y limpieza del área de trabajo',
    ],
    priceFrom: 'Consultar',
    order: 7,
  },
  {
    id: 'consultoria',
    slug: 'consultoria',
    path: '/servicios/consultoria',
    title: 'Consultoría de Diseño',
    name: 'Consultoría',
    shortDescription: 'Asesoría profesional de diseño de interiores para tu proyecto de remodelación en Carabobo, Venezuela.',
    shortDesc: 'Asesoría profesional de diseño.',
    fullDescription: '¿No sabes por dónde empezar? Nuestra consultoría te da la dirección.',
    longDescription: '¿No sabes **por dónde empezar** con tu proyecto de remodelación? Nuestra **consultoría de diseño de interiores** te da la dirección correcta. Analizamos tu espacio, entendemos tus necesidades y te proponemos soluciones tanto funcionales como estéticas. Te entregamos un mood board personalizado, renders 3D fotorrealistas para que visualices el resultado final, selección de materiales y un plan de acción detallado. Todo esto te permite tomar decisiones informadas antes de iniciar la obra y evitar costosos errores.',
    summary: 'Asesoría profesional para tu remodelación.',
    heroImage: `${WP}/2025/11/a7074628ae5503c045cbce2a327c2ea08459cb11.jpg`,
    timeline: '1–2 semanas',
    galleryImages: [
      `${WP}/2025/11/a7074628ae5503c045cbce2a327c2ea08459cb11.jpg`,
    ],
    faqs: [
      { q: '¿Qué incluye la consultoría?', a: 'Mood board personalizado, renders 3D, selección de materiales y plan de acción detallado.' },
      { q: '¿Es presencial o virtual?', a: 'Ofrecemos ambas modalidades, presencial en Carabobo o virtual para cualquier zona.' },
    ],
    icon: 'Palette',
    iconName: 'Palette',
    features: [
      'Análisis completo de tu espacio',
      'Mood board personalizado',
      'Renders 3D fotorrealistas',
      'Selección de materiales y acabados',
      'Presupuesto detallado',
      'Plan de acción por etapas',
    ],
    priceFrom: 'Consultar',
    order: 8,
  },
]

export const galleryImages = [
  { src: `${WP}/2025/11/4f9e75a852947810e2fc262e92ceb26aaf4b9449.jpg`, alt: 'Remodelación de Cocina en San Diego y Valencia, Carabobo', category: 'Cocina' },
  { src: `${WP}/2025/11/c11d4a42c2df886466dc228fe305556c5a1c7dce.jpg`, alt: 'Cocina Integral Premium en Venezuela', category: 'Cocina' },
  { src: `${WP}/2025/11/image-7.jpg`, alt: 'Remodelación de Baño moderno en Carabobo', category: 'Baño' },
  { src: `${WP}/2025/11/af78d08c764a5acd9a01ea460f3ceb209a99bdac.jpg`, alt: 'Baño moderno completo reformado', category: 'Baño' },
  { src: `${WP}/2025/11/image-6.jpg`, alt: 'Instalación eléctrica profesional', category: 'Electricidad' },
  { src: `${WP}/2025/11/a7074628ae5503c045cbce2a327c2ea08459cb11.jpg`, alt: 'Reforma integral de vivienda en Venezuela', category: 'Integral' },
]

export const processSteps = [
  { num: 1, title: 'Contacto Inicial', desc: 'Cuéntanos tu idea por WhatsApp o formulario', icon: 'MessageCircle' },
  { num: 2, title: 'Visita Técnica', desc: 'Visitamos tu espacio y tomamos medidas', icon: 'Ruler' },
  { num: 3, title: 'Diseño y Presupuesto', desc: 'Creamos el diseño y presupuesto detallado', icon: 'Palette' },
  { num: 4, title: 'Aprobación', desc: 'Revisas, ajustamos y aprobamos juntos', icon: 'CheckCircle' },
  { num: 5, title: 'Ejecución', desc: 'Nuestro equipo ejecuta la obra con calidad', icon: 'Hammer' },
  { num: 6, title: 'Entrega', desc: 'Limpieza final y entrega de tu espacio soñado', icon: 'Home' },
]

export const testimonials = [
  { name: 'María González', role: 'San Diego, Carabobo', text: 'Reformat Venezuela transformó nuestra cocina por completo. Excelente calidad y atención. 100% recomendados.', rating: 5 },
  { name: 'Carlos Mendoza', role: 'Valencia, Carabobo', text: 'Remodelación integral perfecta. Muy profesionales, limpios y cumplieron con el plazo acordado.', rating: 5 },
  { name: 'Ana Rodríguez', role: 'San Diego, Carabobo', text: 'El baño quedó espectacular. El equipo es muy amable y profesional. Presupuesto honesto y trabajo impecable.', rating: 5 },
]

export const faqGeneral = [
  { q: '¿Cuánto tiempo tarda una remodelación?', a: 'Depende del proyecto. Una remodelación de baño puede tomar entre 1 y 3 semanas, una cocina entre 2 y 4 semanas, y una reforma integral entre 2 y 3 meses. Te damos un cronograma estimado en el presupuesto.' },
  { q: '¿Ofrecen garantía en los trabajos?', a: 'Sí, todos nuestros trabajos tienen garantía de 1 año mínimo en mano de obra y materiales. Tu satisfacción es nuestra prioridad.' },
  { q: '¿Trabajan solo en San Diego y Valencia?', a: 'Principalmente nos centramos en San Diego y Valencia, Carabobo, pero también atendemos en varias zonas de Venezuela.' },
  { q: '¿El presupuesto es gratis?', a: 'Sí, el presupuesto y la primera visita son completamente gratis y sin compromiso.' },
  { q: '¿Trabajan con materiales que yo compre?', a: 'Sí, podemos usar materiales propios o sugerirte los mejores proveedores según tu presupuesto.' },
]

export default { siteConfig, services, galleryImages, processSteps, testimonials, faqGeneral, waLink, waPhone }
